package com.hcc.hccbanking.model;

import java.util.List;

public enum Partner {
    INECOBANK(
            Bank.builder()
                    .name("InecoBank")
                    .configInfo(
                            Config.builder()
                                    .color("#1b6038")
                                    .imgURL("/img/ineco-logo.svg")
                                    .build()
                    )
                    .credits(List.of(
                                    Credit.builder()
                                            .clientType(ClientType.LEGAL)
                                            .description("Ձևակերպե՛ք միկրովարկեր Ինեկոբանկում Ձեր բիզնեսի կապիտալ ներդրումների և շրջանառու միջոցների համալրման նպատակով։")
                                            .id(1)
                                            .creditType(CreditType.BUSINESS)
                                            .creditPercent(21.00)
                                            .build(),
                                    Credit.builder()
                                            .clientType(ClientType.PERSONAL)
                                            .description("Ձևակերպե՛ք արագ սպառողական վարկեր Ինեկոբանկում՝ առանց գրավադրման, երաշխավորության և եկամուտը հաստատող փաստաթղթի, և ստացե՛ք հասանելի գումարի չափով վարկ միջինում 15 րոպեում։")
                                            .id(2)
                                            .creditType(CreditType.CONSUMER)
                                            .creditPercent(19.00)
                                            .build(),
                                    Credit.builder()
                                            .clientType(ClientType.PERSONAL)
                                            .description("Դիմե՛ք և հաշված վայրկյանների ընթացքում ստացե՛ք մինչև 10 000 000 ՀՀ դրամ 1 CLICK օնլայն վարկ՝ առանց երաշխավորի և հավելյալ թղթաբանության։")
                                            .id(3)
                                            .creditType(CreditType.CLICK)
                                            .creditPercent(19.00)
                                            .build(),
                                    Credit.builder()
                                            .clientType(ClientType.PERSONAL)
                                            .description("Ձևակերպե՛ք անշարժ գույքի գրավով վերականգնվող վարկային գիծ Ինեկոբանկում MasterCard և Visa վճարային համակարգեի քարտերով։ ")
                                            .creditType(CreditType.COLLATERAL)
                                            .id(4)
                                            .creditPercent(17.28)
                                            .build(),
                                    Credit.builder()
                                            .clientType(ClientType.PERSONAL)
                                            .description("Ձևակերպեք վարկային գիծ ArCa Classic վճարային քարտերով, ստացեք հնարավորություն կատարելու անկանխիկ վճարումներ ՀՀ ողջ տարածքում և Արցախում։")
                                            .id(5)
                                            .creditType(CreditType.NONCOLLATERAL)
                                            .creditPercent(19.00)
                                            .build(),
                                    Credit.builder()
                                            .clientType(ClientType.PERSONAL)
                                            .description("Ինեկոբանկն առաջարկում է դիմել «Ապառիկը տեղում» վարկի և հաշված րոպեների ընթացքում անհրաժեշտ ֆինանսավորումը հասանելի կլինի՝ հենց վաճառքի կամ սպասարկման կետում՝ առանց բանկ այցելելու անհրաժեշտության։")
                                            .creditType(CreditType.INSTALLMENT)
                                            .id(6)
                                            .creditPercent(23.75)
                                            .build()
                            )
                    )
                    .calculatorInfo(
                            CalculatorInformation.builder()
                                    .name("Հաշվիչ")
                                    .build()
                    )
                    .build()
    ),
    ABBBANK(
            Bank.builder()
                    .name("AbbBank")
                    .configInfo(
                            Config.builder()
                                    .color("#ed2b12")
                                    .imgURL("/img/logo_abb.png")
                                    .build()
                    )
                    .credits(List.of(
                                    Credit.builder()
                                            .clientType(ClientType.PERSONAL)
                                            .description("Առաջնակարգ (ավանդային և բանկային հաշիվներում առկա դրամական միջոցների) գրավով ապահոված վարկեր")
                                            .creditType(CreditType.CONSUMER)
                                            .id(1)
                                            .creditPercent(19.00)
                                            .build(),
                                    Credit.builder()
                                            .clientType(ClientType.PERSONAL)
                                            .description("Ոսկու գրավով վարկ Հայ Բիզնես բանկում")
                                            .id(2)
                                            .creditType(CreditType.COLLATERAL)
                                            .creditPercent(23.26)
                                            .build(),
                                    Credit.builder()
                                            .clientType(ClientType.PERSONAL)
                                            .description("Ուսանողական վարկեր Հայ Բիզնես բանկում")
                                            .id(3)
                                            .creditType(CreditType.NONCOLLATERAL)
                                            .creditPercent(19.00)
                                            .build(),
                                    Credit.builder()
                                            .clientType(ClientType.PERSONAL)
                                            .description("«ՀՀ Գյուղատնտեսության ոլորտում հակակարկտային ցանցերի ներդրման համար տրամադրվող վարկերի տոկոսադրույքների սուբսիդավորում» ծրագրի շրջանակում տրամադրվող վարկեր")
                                            .creditType(CreditType.AGRICULTURAL)
                                            .id(4)
                                            .creditPercent(12.00)
                                            .build(),
                                    Credit.builder()
                                            .clientType(ClientType.PERSONAL)
                                            .description("Բնակելի անշարժ գույքի վերանորոգման/արդիականացման համար վարկեր Ազգային հիփոթեքային ընկերություն ՎՎԿ ՓԲԸ-ի ՙՋերմ Օջախ՚ ծրագրի շրջանակներում")
                                            .creditType(CreditType.MORTGAGE)
                                            .creditPercent(15.90)
                                            .id(5)
                                            .build(),
                                    Credit.builder()
                                            .clientType(ClientType.LEGAL)
                                            .description("Իրավաբանական անձանց տրվող բիզնես վարկ")
                                            .creditType(CreditType.BUSINESS)
                                            .creditPercent(9.00)
                                            .id(6)
                                            .build(),
                                    Credit.builder()
                                            .clientType(ClientType.LEGAL)
                                            .description("Իրավաբանական անձանց  տրվող արտահանման բիզնես վարկ")
                                            .creditType(CreditType.EXPORT)
                                            .creditPercent(15.90)
                                            .id(7)
                                            .build(),
                                    Credit.builder()
                                            .clientType(ClientType.LEGAL)
                                            .description("Իտալական UBI Բանկի հետ իրականացվող վարկավորման ծրագրի շրջանակներում տրամադրվող վարկեր")
                                            .creditType(CreditType.IMPORT)
                                            .creditPercent(10.00)
                                            .id(8)
                                            .build(),
                                    Credit.builder()
                                            .clientType(ClientType.LEGAL)
                                            .description("Գերմանահայկական Հիմնադրամի «Վերականգնվող էներգիայի զարգացում » ծրագրի շրջանակներում տրամադրվող վարկեր, չվերականգնվող վարկային գծեր")
                                            .creditType(CreditType.GREEN)
                                            .creditPercent(10.5)
                                            .id(9)
                                            .build(),
                                    Credit.builder()
                                            .clientType(ClientType.LEGAL)
                                            .description("ԻՐԱՎԱԲԱՆԱԿԱՆ ԱՆՁԱՆՑ ԵՎ ԱՆՀԱՏ ՁԵՌՆԱՐԿԱՏԵՐԵՐԻՆ ՏՐԱՄԱԴՐՎՈՂ ՕՎԵՐԴՐԱՖՏ ")
                                            .creditType(CreditType.OVERDRAFT)
                                            .creditPercent(10.5)
                                            .id(10)
                                            .build()

                            )
                    )
                    .calculatorInfo(
                            CalculatorInformation.builder()
                                    .name("Հաշվիչ")
                                    .build()
                    )
                    .build()
    ),
    IDBANK(
            Bank.builder()
                    .name("IDBank")
                    .configInfo(
                            Config.builder()
                                    .color("#f57424")
                                    .imgURL("/img/id_logo.png")
                                    .build()
                    )
                    .credits(List.of(
                                    Credit.builder()
                                            .clientType(ClientType.PERSONAL)
                                            .description("Վարկեր անշարժ գույքի գրավով` ինչպես եկամուտների հիմնավորմամբ, այնպես էլ` առանց եկամուտների հիմնավորման")
                                            .creditType(CreditType.CONSUMER)
                                            .creditPercent(15.5)
                                            .id(1)
                                            .build(),
                                    Credit.builder()
                                            .clientType(ClientType.PERSONAL)
                                            .description("Ստացեք հարմար վարկատեսակը դրամական միջոցների ապահովությամբ։ Գրավադրվել կարող են ավանդը, բանկային հաշիվներին ներդրված դրամական միջոցները։ Վարկի տոկոսագումարները կարող եք մարել անուիտետային, զսպանակաձև և արտոնյալ եղանակներով։")
                                            .creditType(CreditType.COLLATERAL)
                                            .creditPercent(2.00)
                                            .id(2)
                                            .build(),
                                    Credit.builder()
                                            .clientType(ClientType.PERSONAL)
                                            .description("Արագ Վարկ տրամադրվում է առանց գրավի՝ եկամտի հիման վրա։ Վարկ ստանալու համար պահանջվում է ունենալ դրական վարկային պատմություն և համապատասխան վարկարժանության գնահատական։\n")
                                            .creditType(CreditType.NONCOLLATERAL)
                                            .creditPercent(21.7)
                                            .id(3)
                                            .build(),
                                    Credit.builder()
                                            .clientType(ClientType.PERSONAL)
                                            .description("Վարկերը տրամադրվում են ֆիզիկական անձանց բնակելի անշարժ գույքի ձեռքբերման նպատակով:")
                                            .creditType(CreditType.MORTGAGE)
                                            .creditPercent(7.4)
                                            .id(4)
                                            .build(),
                                    Credit.builder()
                                            .clientType(ClientType.LEGAL)
                                            .description("Ստացե՛ք շահավետ պայմաններով վարկեր՝ Ձեր բիզնեսն ավելի արդյունավետ և եկամտաբեր դարձնելու համար։")
                                            .creditType(CreditType.BUSINESS)
                                            .creditPercent(7.4)
                                            .id(5)
                                            .build(),
                                    Credit.builder()
                                            .clientType(ClientType.LEGAL)
                                            .description("Ստացե՛ք շահավետ պայմաններով օվերդրաֆտ՝ կարճաժամկետ խնդիրների լուծման համար։ Օվերդրաֆտը տրամադրվում է առանց ամսական սպասարկման վճարի։")
                                            .creditType(CreditType.OVERDRAFT)
                                            .creditPercent(7.4)
                                            .id(6)
                                            .build(),
                                    Credit.builder()
                                            .clientType(ClientType.LEGAL)
                                            .description("Էներգաարդյունավետ վարկ ՓՄՁ-ների համար Ծրագիր")
                                            .creditType(CreditType.GREEN)
                                            .id(7)
                                            .creditPercent(7.4)
                                            .build()

                            )
                    )
                    .calculatorInfo(
                            CalculatorInformation.builder()
                                    .name("Հաշվիչ")
                                    .build()
                    )
                    .build()

    ),
    ACBABANK(
            Bank.builder()
                    .name("ACBAbank")
                    .configInfo(
                            Config.builder()
                                    .color("#37a789")
                                    .imgURL("/img/acba_b_logo .png")
                                    .build()
                    )
                    .credits(List.of(
                                    Credit.builder()
                                            .clientType(ClientType.PERSONAL)
                                            .description("ԱԿԲԱ Բանկը տրամադրում է Հիփոթեքային վարկեր այն ֆիզիկական անձանց, ովքեր ունեն կայուն եկամուտ: Վարկերը տրամադրվում են անշարժ գույքի (բնակարան, բնակելի տուն, առանձնատուն, այլ) ձեռքբերման (գնման) նպատակով:")
                                            .creditType(CreditType.CONSUMER)
                                            .id(1)
                                            .creditPercent(13.5)
                                            .build(),
                                    Credit.builder()
                                            .clientType(ClientType.PERSONAL)
                                            .description("Ավանդի գրավով սպառողական վարկը հարմարավետ տարբերակ է լուծելու Ձեր դրամական խնդիրները՝ պահպանելով Ձեր ավանդային հաշիվները:")
                                            .creditType(CreditType.COLLATERAL)
                                            .creditPercent(22.95)
                                            .id(2)
                                            .build(),
                                    Credit.builder()
                                            .clientType(ClientType.PERSONAL)
                                            .description("Արագ սպառողական վարկեր մինչև 5 մլն ՀՀ դրամ")
                                            .creditType(CreditType.NONCOLLATERAL)
                                            .creditPercent(24.00)
                                            .id(3)
                                            .build(),
                                    Credit.builder()
                                            .clientType(ClientType.PERSONAL)
                                            .description("Վարկերը տրամադրվում են ֆիզիկական անձանց բնակելի անշարժ գույքի ձեռքբերման նպատակով:")
                                            .creditType(CreditType.MORTGAGE)
                                            .creditPercent(7.4)
                                            .id(4)
                                            .build(),
                                    Credit.builder()
                                            .clientType(ClientType.PERSONAL)
                                            .description("«ԱՐԱԳ ՕՎԵՐԴՐԱՖՏ» քարտային օվերդրաֆտի տրամադրման համար դիմելու դեպքում Դուք կունենաք մի շարք առավելություններ.")
                                            .creditType(CreditType.OVERDRAFT)
                                            .creditPercent(7.4)
                                            .id(5)
                                            .build(),
                                    Credit.builder()
                                            .clientType(ClientType.PERSONAL)
                                            .description("Ցանկանու՞մ եք գնել որևէ կենցաղային գույք կամ համակարգչային տեխնիկա, կահույք, շինանյութ, օգտվել տուրիստական, բժշկական կամ այլ ծառայություններից, սակայն չունեք համապատասխան միջոցներ.")
                                            .creditType(CreditType.INSTALLMENT)
                                            .creditPercent(24.00)
                                            .id(6)
                                            .build(),
                                    Credit.builder()
                                            .clientType(ClientType.PERSONAL)
                                            .description("Բանկը տրամադրում է գյուղատնտեսական վարկեր բոլոր այն ֆիզիկական և իրավաբանական անձանց, որոնք զբաղվում են կամ նախատեսում են զբաղվել գյուղատնտեսական արտադրությամբ կամ գյուղատնտեսական հումքի վերամշակմամբ:")
                                            .creditType(CreditType.AGRICULTURAL)
                                            .creditPercent(24.00)
                                            .id(7)
                                            .build(),
                                    Credit.builder()
                                            .clientType(ClientType.LEGAL)
                                            .description("Անհրաժե՞շտ են կարճաժամկետ ֆինանսական միջոցներ` բիզնեսի ծախսերը հոգալու նպատակով:")
                                            .creditType(CreditType.OVERDRAFT)
                                            .creditPercent(19.00)
                                            .id(8)
                                            .build(),
                                    Credit.builder()
                                            .clientType(ClientType.LEGAL)
                                            .description("Ընդլայնեք Ձեր բիզնեսի ներմուծման ծավալները մեր կողմից առաջարկվող ներմուծման վարկային գծերի միջոցով,")
                                            .creditType(CreditType.IMPORT)
                                            .creditPercent(8.00)
                                            .id(9)
                                            .build(),
                                    Credit.builder()
                                            .clientType(ClientType.LEGAL)
                                            .description("Ընդլայնեք Ձեր բիզնեսի արտահանման ծավալները մեր կողմից առաջարկվող արտահանման վարկային գծերի միջոցով,")
                                            .creditType(CreditType.EXPORT)
                                            .creditPercent(8.00)
                                            .id(10)
                                            .build(),
                                    Credit.builder()
                                            .clientType(ClientType.LEGAL)
                                            .description("Իրականացրե՛ք էներգաարդյունավետ ներդրումներ՝ կրճատելով բիզնեսի ծախսերը և բարձրացնելով բիզնեսի արդյունավետությունը։")
                                            .creditType(CreditType.GREEN)
                                            .creditPercent(18.00)
                                            .id(11)
                                            .build()

                            )
                    )
                    .calculatorInfo(
                            CalculatorInformation.builder()
                                    .name("Հաշվիչ")
                                    .build()
                    )
                    .build()
    ),
    AEBBANK(
            Bank.builder()
                    .name("AEBbank")
                    .configInfo(
                            Config.builder()
                                    .color("#174885")
                                    .imgURL("/img/aeb-logo .png")
                                    .build()
                    )
                    .credits(List.of(
                                    Credit.builder()
                                            .clientType(ClientType.PERSONAL)
                                            .description("Ուսումնառության ընթացքում կմարվեն միայն տոկոսները (առավելագույնը 4 տարի), իսկ ուսումնառության ավարտից հետո կիրականացվեն վարկի մայր գումարի և տոկոսագումարների հավասարաչափ մարումներ")
                                            .creditType(CreditType.CONSUMER)
                                            .creditPercent(9.38)
                                            .id(1)
                                            .build(),
                                    Credit.builder()
                                            .clientType(ClientType.PERSONAL)
                                            .description("Շտապ լուծում ձեր առօրյա խնդիրներին․ սպառողական վարկեր ոսկյա իրերի գրավադրմամբ։ Տրամադրվում է 18 տարին լրացած ՀՀ քաղաքացի և ռեզիդենտ ֆիզիկական անձանց։ ")
                                            .creditType(CreditType.COLLATERAL)
                                            .creditPercent(23.94)
                                            .id(2)
                                            .build(),
                                    Credit.builder()
                                            .clientType(ClientType.PERSONAL)
                                            .description("Սպառողական անգրավ արագ վարկեր մինչև 1 մլն ՀՀ դրամ 24 ժամվա ընթացքում 24 ամիս ժամկետով: ")
                                            .creditType(CreditType.NONCOLLATERAL)
                                            .creditPercent(20.00)
                                            .id(3)
                                            .build(),
                                    Credit.builder()
                                            .clientType(ClientType.PERSONAL)
                                            .description("<<Մատչելի բնակարան երիտասարդ ընտանիքներին>> պետական նպատակային ծրագրի շրջանակներում անշարժ գույքի ձեռքբերման նպատակով տրամադրվող հիփոթեքային վարկ")
                                            .creditType(CreditType.MORTGAGE)
                                            .creditPercent(7.4)
                                            .id(4)
                                            .build(),
                                    Credit.builder()
                                            .clientType(ClientType.PERSONAL)
                                            .description("Կահույքի,կենցաղային ապրանքների,տեխնիկայի, շինանյութի ձեռքբերում, ծառայությունների մատուցման ֆինանսավորում")
                                            .creditType(CreditType.INSTALLMENT)
                                            .id(5)
                                            .creditPercent(24.00)
                                            .build(),
                                    Credit.builder()
                                            .clientType(ClientType.PERSONAL)
                                            .description("Գյուղատնտեսական վարկ AEB բանկում")
                                            .creditType(CreditType.AGRICULTURAL)
                                            .creditPercent(24.00)
                                            .id(6)
                                            .build(),
                                    Credit.builder()
                                            .clientType(ClientType.LEGAL)
                                            .description("Արտահանման ֆինանսավորման վարկ AEB բանկում")
                                            .creditType(CreditType.EXPORT)
                                            .creditPercent(14.57)
                                            .id(7)
                                            .build(),
                                    Credit.builder()
                                            .clientType(ClientType.LEGAL)
                                            .description("Արևային էլեկտրակայանների և արևային ջրատաքացուցիչների  ձեռքբերում")
                                            .creditType(CreditType.GREEN)
                                            .id(8)
                                            .creditPercent(8.5)
                                            .build()
                            )
                    )
                    .calculatorInfo(
                            CalculatorInformation.builder()
                                    .name("Հաշվիչ")
                                    .build()
                    )
                    .build()
    ),
    ARARATBANK(
            Bank.builder()
                    .name("ARARATbank")
                    .configInfo(
                            Config.builder()
                                    .color("#f8b912")
                                    .imgURL("/img/AraratBank-Logo .jpg")
                                    .build()
                    )
                    .credits(List.of(
                                    Credit.builder()
                                            .clientType(ClientType.PERSONAL)
                                            .description("Ուսման վարձի վճարում")
                                            .creditType(CreditType.CONSUMER)
                                            .creditPercent(17.00)
                                            .id(1)
                                            .build(),
                                    Credit.builder()
                                            .clientType(ClientType.PERSONAL)
                                            .description("Վարկերը  տրամադրվում են գնահատված արժեքի մինչև 150%-ի չափով միայն ռեզիդենտ ՀՀ քաղաքացի ֆիզիկական անձանց, ընդ որում՝")
                                            .creditType(CreditType.COLLATERAL)
                                            .creditPercent(18.5)
                                            .id(2)
                                            .build(),
                                    Credit.builder()
                                            .clientType(ClientType.PERSONAL)
                                            .description("Սպառողական անգրավ արագ վարկեր մինչև 1 մլն ՀՀ դրամ 24 ժամվա ընթացքում 24 ամիս ժամկետով: ")
                                            .creditType(CreditType.NONCOLLATERAL)
                                            .id(3)
                                            .creditPercent(23.75)
                                            .build(),
                                    Credit.builder()
                                            .clientType(ClientType.PERSONAL)
                                            .description("<<Մատչելի բնակարան երիտասարդ ընտանիքներին>> պետական նպատակային ծրագրի շրջանակներում անշարժ գույքի ձեռքբերման նպատակով տրամադրվող հիփոթեքային վարկ")
                                            .creditType(CreditType.MORTGAGE)
                                            .creditPercent(7.4)
                                            .id(4)
                                            .build(),
                                    Credit.builder()
                                            .clientType(ClientType.PERSONAL)
                                            .description("Կահույքի,կենցաղային ապրանքների,տեխնիկայի, շինանյութի ձեռքբերում, ծառայությունների մատուցման ֆինանսավորում")
                                            .creditType(CreditType.INSTALLMENT)
                                            .creditPercent(24.00)
                                            .id(5)
                                            .build(),
                                    Credit.builder()
                                            .clientType(ClientType.PERSONAL)
                                            .description("Գյուղատնտեսական արտադրությամբ զբաղվող ֆիզիկական անձանց սպառողական նպատակներով տրամադրվող վարկեր")
                                            .creditType(CreditType.AGRICULTURAL)
                                            .creditPercent(22.08)
                                            .id(6)
                                            .build(),
                                    Credit.builder()
                                            .clientType(ClientType.PERSONAL)
                                            .description("ԱՐԱՐԱՏԲԱՆԿ-ն առաջարկում է օվերդրաֆտներ ՀՀ քաղաքացի և ռեզիդենտ այն ֆիզիկական անձանց, ում գործատուի հետ Բանկն իրականացնում է աշխատավարձային նախագիծ")
                                            .creditType(CreditType.OVERDRAFT)
                                            .creditPercent(22.28)
                                            .id(7)
                                            .build(),
                                    Credit.builder()
                                            .clientType(ClientType.LEGAL)
                                            .description("ArCa Green Line վճարային պլաստիկ քարտով տրամադրվող օվերդրաֆտի միջոցով հնարավորություն կունենաք անկանխիկ եղանակով կատարել մաքսային վճարումներ։")
                                            .creditType(CreditType.OVERDRAFT)
                                            .creditPercent(22.28)
                                            .id(8)
                                            .build(),
                                    Credit.builder()
                                            .clientType(ClientType.LEGAL)
                                            .description("Շտապե՛ք լուծել Ձեր բիզնեսի ֆինանսավորման խնդիրներն ԱՐԱՐԱՏԲԱՆԿ-ի օգնությամբ:")
                                            .creditType(CreditType.BUSINESS)
                                            .creditPercent(11.00)
                                            .id(9)
                                            .build(),
                                    Credit.builder()
                                            .clientType(ClientType.LEGAL)
                                            .description("Վարկեր փոքր և միջին բիզնեսի համար «Էներգաարդյունավետություն ՓՄՁ-ների համար» ծրագրի շրջանակում:")
                                            .creditType(CreditType.GREEN)
                                            .creditPercent(8.5)
                                            .id(10)
                                            .build()
                            )
                    )
                    .calculatorInfo(
                            CalculatorInformation.builder()
                                    .name("Հաշվիչ")
                                    .build()
                    )
                    .build()
    ),
    CONVERSEBANK(
            Bank.builder()
                    .name("CONVERSEbank")
                    .configInfo(
                            Config.builder()
                                    .color("#308abc")
                                    .imgURL("/img/converse-logo.png")
                                    .build()
                    )
                    .credits(List.of(
                                    Credit.builder()
                                            .clientType(ClientType.PERSONAL)
                                            .description("Օգտվելով Կոնվերս Բանկի ավտովարկերից, Դուք կարող եք իրականացնել Ձեր երազանքը՝ ձեռք բերելով նոր ավտոմեքենա, թարմացնել Ձեր ավտոմեքենան,")
                                            .creditType(CreditType.CONSUMER)
                                            .creditPercent(17.00)
                                            .id(1)
                                            .build(),
                                    Credit.builder()
                                            .clientType(ClientType.PERSONAL)
                                            .description("Դուք կարող եք ձեռք բերել վարկեր՝ գրավ դնելով Ձեր ոսկին:")
                                            .creditType(CreditType.COLLATERAL)
                                            .creditPercent(18.5)
                                            .id(2)
                                            .build(),
                                    Credit.builder()
                                            .clientType(ClientType.PERSONAL)
                                            .description("Մեր ուսանողական վարկերը կօգնեն Ձեզ հաղթահարել ֆինանսական խնդիրները մասնագիտություն ձեռք բերելու ճանապարհին: ")
                                            .creditType(CreditType.NONCOLLATERAL)
                                            .creditPercent(23.75)
                                            .id(3)
                                            .build(),
                                    Credit.builder()
                                            .clientType(ClientType.PERSONAL)
                                            .description("Անշարժ գույքի ձեռքբերման և վերանորոգման վարկեր կառուցապատողից")
                                            .creditType(CreditType.MORTGAGE)
                                            .creditPercent(18.97)
                                            .id(4)
                                            .build(),
                                    Credit.builder()
                                            .clientType(ClientType.PERSONAL)
                                            .description("Վարկառուն պետք է լինի 21 տարին լրացած ՀՀ ռեզիդենտ, ով դիմում է Բանկին՝ վերջինիս հետ համագործակցող վաճառակետերից ապառիկ եղանակով ապրանքներ ձեռք բերելու նպատակով:")
                                            .creditType(CreditType.INSTALLMENT)
                                            .creditPercent(24.00)
                                            .id(5)
                                            .build(),
                                    Credit.builder()
                                            .clientType(ClientType.PERSONAL)
                                            .description("Վարկը տրամադրվում է Կոնվերս Բանկ ՓԲԸ (այսուհետ՝ Բանկ) կողմից ՀՀ ռեզիդենտ ֆիզիկական և իրավաբանական անձանց, անհատ ձեռնարկատերերին հետևյալ պայմաններով.")
                                            .creditType(CreditType.AGRICULTURAL)
                                            .creditPercent(24.00)
                                            .id(6)
                                            .build(),
                                    Credit.builder()
                                            .clientType(ClientType.LEGAL)
                                            .description("Ընդլայնեք արտահանման ծավալները. պարզապես ներկայացրեք ՀԱԱԳ-ի կողմից տրամադրվելիք ապահովագրական վկայագիրը և օգտվեք արտահանման/նախաարտահանման ֆինանսավորումից: ")
                                            .creditType(CreditType.EXPORT)
                                            .creditPercent(24.00)
                                            .id(7)
                                            .build()
                            )
                    )
                    .calculatorInfo(
                            CalculatorInformation.builder()
                                    .name("Հաշվիչ")
                                    .build()
                    )
                    .build()
    ),
    UNIBANK(
            Bank.builder()
                    .name("UNIbank")
                    .configInfo(
                            Config.builder()
                                    .color("#1e3c7d")
                                    .imgURL("/img/uni-logo .png")
                                    .build()
                    )
                    .credits(List.of(
                                    Credit.builder()
                                            .clientType(ClientType.PERSONAL)
                                            .description("Սպառողական վարկ` կենցաղային ապրանքներ և շինանյութեր ձեռքբերելու համար:")
                                            .creditType(CreditType.CONSUMER)
                                            .creditPercent(18.00)
                                            .id(1)
                                            .build(),
                                    Credit.builder()
                                            .clientType(ClientType.PERSONAL)
                                            .description("Ոսկու գրավով տրամադրվող սպառողական վարկ բոլոր նպատակների համար")
                                            .creditType(CreditType.COLLATERAL)
                                            .creditPercent(15.00)
                                            .id(2)
                                            .build(),
                                    Credit.builder()
                                            .clientType(ClientType.PERSONAL)
                                            .description("Սպառողական վարկ 0% 0% 0,95%-12` հատուկ ակցիաների շրջանակում ապրանքներ ձեռքբերելու համար: Տարեկան տոկոսադրույքը` 0%, կանխավճարը` 0%:")
                                            .creditType(CreditType.NONCOLLATERAL)
                                            .creditPercent(24.00)
                                            .id(3)
                                            .build(),
                                    Credit.builder()
                                            .clientType(ClientType.PERSONAL)
                                            .description("Յունիբանկի հիփոթեքային վարկերի մեծ տեսականու շնորհիվ անշարժ գույքի ձեռքբերումը դարձել է պարզ և մատչելի: Բանկը գրավիչ պայմաններով հիփոթեքային վարկեր է տրամադրում Երևանում և մարզերում բնակելի անշարժ գույք, բիզնես տարածք գնելու, կառուցապատելու կամ վերանորոգելու համար:")
                                            .creditType(CreditType.MORTGAGE)
                                            .creditPercent(12.00)
                                            .id(4)
                                            .build(),
                                    Credit.builder()
                                            .clientType(ClientType.PERSONAL)
                                            .description("Սպառողական վարկ` տեխնիկա և բջջային հեռախոսներ ձեռքբերելու համար:")
                                            .creditType(CreditType.INSTALLMENT)
                                            .creditPercent(10.00)
                                            .id(5)
                                            .build(),
                                    Credit.builder()
                                            .clientType(ClientType.LEGAL)
                                            .description("Արտահանման պայմանագրի կատարման համար ապրանքների և/կամ ծառայությունների ձեռքբերման ֆինանսավորում և/կամ վերաֆինանսավորում:")
                                            .creditType(CreditType.EXPORT)
                                            .creditPercent(13.00)
                                            .id(6)
                                            .build(),
                                    Credit.builder()
                                            .clientType(ClientType.LEGAL)
                                            .description("Վարկ «Անգրավ +» Վարկը նախատեսված է բիզնես նպատակների, ինչպես նաև այլ բանկերում վարկերի վերաֆինանսավորման համար")
                                            .creditType(CreditType.NONCOLLATERAL)
                                            .creditPercent(17.7)
                                            .id(7)
                                            .build(),
                                    Credit.builder()
                                            .clientType(ClientType.LEGAL)
                                            .description("«Visa Busines Card» վերականգնվող վարկային գիծ (օվերդրաֆտ)")
                                            .creditType(CreditType.OVERDRAFT)
                                            .id(8)
                                            .creditPercent(13.00)
                                            .build()
                            )
                    )
                    .calculatorInfo(
                            CalculatorInformation.builder()
                                    .name("Հաշվիչ")
                                    .build()
                    )
                    .build()
    );


    private  Bank bank;

    Partner(Bank bank) {
        this.bank = bank;
    }

    public Bank getBank() {
        return bank;
    }
}
