#spring.datasource.driver-class-name=
#spring.datasource.url =
#spring.datasource.username =
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect =
#spring.jpa.hibernate.ddl-auto =


# ✅ Server Port
server.port=9090

# ✅ OAuth2 Resource Server JWT config
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/myrealm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8081/realms/myrealm/protocol/openid-connect/certs

# ✅ Custom JWT Converter properties (used in your JwtConverter)
jwt.auth.converter.principle-attribute=preferred_username
jwt.auth.converter.resource-id=my-client
