#spring.datasource.driver-class-name=
#spring.datasource.url =
#spring.datasource.username =
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect =
#spring.jpa.hibernate.ddl-auto =

server.port=

spring.security.oauth2.resourceserver.jwt.issuer-uri=
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=

# Tell Spring Security to use the 'roles' claim as authorities
spring.security.oauth2.resourceserver.jwt.authorities-claim-name=
spring.security.oauth2.resourceserver.jwt.claims-authority-prefix=
keycloak.client-id=


# (Optional) Log level for debugging
logging.level.org.springframework.security=DEBUG


