name: Build and Push Docker Image to Docker Hub

on:
  push:
    tags:
      - 'v*'   # Only trigger on tags like v1, v1.2, v2.0.1

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Docker tag from Git tag
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "DOCKER_TAG=$TAG_NAME" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and tag Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/banking
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:${DOCKER_TAG} .

      - name: Push Docker image to Docker Hub
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/banking
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${DOCKER_TAG}

      - name: Logout from Docker Hub
        run: docker logout
