name: Build and Push Docker Image to Docker Hub

on:
  push:
    tags:
      - 'v*'   # Triggers on tags like v1, v2.0, v1.2.3
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version tag
        id: vars
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build and tag Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/banking
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:${TAG_NAME} .

      - name: Push Docker image to Docker Hub
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/banking
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${TAG_NAME}

      - name: Logout from Docker Hub
        run: docker logout
