name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Docker tag
        id: docker_tag
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION_TAG="${GITHUB_REF#refs/tags/}"
          elif [[ "${GITHUB_REF}" == refs/heads/* ]]; then
            VERSION_TAG=$(git rev-parse --short HEAD)
          else
            # For pull requests or other refs like refs/pull/1/merge
            VERSION_TAG="pr-${{ github.event.pull_request.number || 'unknown' }}-$(git rev-parse --short HEAD)"
          fi
          echo "DOCKER_TAG=$VERSION_TAG" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and tag Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/banking
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:${DOCKER_TAG} .

      - name: Push Docker image to Docker Hub
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/banking
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${DOCKER_TAG}

      - name: Logout from Docker Hub
        run: docker logout
